// reference/tinyship-main/apps/nuxt-app/pages/admin/pricing/index.vue
<template>
  <div class="container mx-auto py-10 px-5">
    <div class="flex items-center justify-between mb-6">
      <div>
        <h1 class="text-2xl font-bold">{{ $t('admin.pricing.title') }}</h1>
        <p class="text-muted-foreground text-sm mt-1">
          {{ $t('admin.pricing.description') }}
          <span :class="['inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold ml-2', pricingMode === 'dynamic' ? 'bg-primary text-primary-foreground' : 'bg-secondary text-secondary-foreground']">
            {{ pricingMode === 'dynamic' ? $t('admin.pricing.mode.dynamic') : $t('admin.pricing.mode.static') }}
          </span>
        </p>
      </div>
      <div class="flex gap-2">
        <button class="inline-flex items-center justify-center rounded-md text-sm font-medium border border-input bg-background hover:bg-accent h-10 px-4" :disabled="importing" @click="handleImport">
          <Upload class="h-4 w-4 mr-2" />{{ importing ? $t('admin.pricing.importing') : $t('admin.pricing.importStatic') }}
        </button>
        <NuxtLink :to="localePath('/admin/pricing/new')" class="inline-flex items-center justify-center rounded-md text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4">
          <Plus class="h-4 w-4 mr-2" />{{ $t('admin.pricing.createPlan') }}
        </NuxtLink>
      </div>
    </div>

    <div v-if="uncoveredLocales.length > 0 && pricingMode === 'dynamic'" class="flex items-center gap-2 p-3 mb-4 bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-800 rounded-md">
      <AlertTriangle class="h-4 w-4 text-yellow-600" />
      <span class="text-sm text-yellow-800 dark:text-yellow-200">{{ $t('admin.pricing.localeCoverageWarning') }} [{{ uncoveredLocales.join(', ') }}]</span>
    </div>

    <div class="flex gap-2 mb-4">
      <button :class="['inline-flex items-center justify-center rounded-md text-sm font-medium h-9 px-3', activeTab === 'subscription' ? 'bg-primary text-primary-foreground' : 'border border-input bg-background hover:bg-accent']" @click="activeTab = 'subscription'">{{ $t('admin.pricing.tabs.subscription') }} ({{ subscriptionPlans.length }})</button>
      <button :class="['inline-flex items-center justify-center rounded-md text-sm font-medium h-9 px-3', activeTab === 'credits' ? 'bg-primary text-primary-foreground' : 'border border-input bg-background hover:bg-accent']" @click="activeTab = 'credits'">{{ $t('admin.pricing.tabs.credits') }} ({{ creditPlans.length }})</button>
    </div>

    <div v-if="loading" class="animate-pulse text-muted-foreground">{{ $t('common.loading') }}</div>

    <p v-else-if="!displayedPlans.length" class="text-muted-foreground py-8 text-center">{{ $t('admin.pricing.noPlans') }}</p>

    <div v-else class="border rounded-lg overflow-hidden">
      <table class="w-full text-sm">
        <thead class="bg-muted/50">
          <tr>
            <th class="px-4 py-3 text-left font-medium">{{ $t('admin.pricing.table.name') }}</th>
            <th class="px-4 py-3 text-left font-medium">{{ $t('admin.pricing.table.provider') }}</th>
            <th class="px-4 py-3 text-left font-medium">{{ $t('admin.pricing.table.price') }}</th>
            <th class="px-4 py-3 text-left font-medium">{{ $t('admin.pricing.table.type') }}</th>
            <th class="px-4 py-3 text-left font-medium">{{ $t('admin.pricing.table.locales') }}</th>
            <th class="px-4 py-3 text-left font-medium">{{ $t('admin.pricing.table.status') }}</th>
            <th class="px-4 py-3 text-right font-medium">{{ $t('admin.pricing.table.actions') }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="plan in displayedPlans" :key="plan.id" class="border-t">
            <td class="px-4 py-3">
              <div class="font-medium">{{ plan.i18n?.en?.name || plan.id }}</div>
              <span v-if="plan.recommended" class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold mt-1">{{ $t('admin.pricing.fields.recommended') }}</span>
            </td>
            <td class="px-4 py-3"><span class="inline-flex items-center rounded-full border bg-secondary px-2.5 py-0.5 text-xs font-semibold">{{ plan.provider }}</span></td>
            <td class="px-4 py-3">
              <span v-if="plan.originalPrice" class="line-through text-muted-foreground mr-1">{{ plan.currency }} {{ plan.originalPrice }}</span>
              <span class="font-medium">{{ plan.currency }} {{ plan.amount }}</span>
            </td>
            <td class="px-4 py-3">
              <span class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold">{{ plan.durationType }}</span>
              {{ plan.durationType === 'credits' ? ` (${plan.credits})` : plan.durationMonths ? ` (${plan.durationMonths}mo)` : '' }}
            </td>
            <td class="px-4 py-3">
              <span v-if="plan.locales" class="text-xs">{{ plan.locales.join(', ') }}</span>
              <span v-else class="text-muted-foreground text-xs">{{ $t('admin.pricing.table.allLocales') }}</span>
            </td>
            <td class="px-4 py-3">
              <label class="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" :checked="plan.isActive" class="sr-only peer" @change="handleToggleActive(plan)" />
                <div class="w-9 h-5 bg-gray-200 rounded-full peer peer-checked:bg-primary transition-colors" />
              </label>
            </td>
            <td class="px-4 py-3 text-right">
              <NuxtLink :to="localePath(`/admin/pricing/${plan.id}`)" class="inline-flex items-center justify-center rounded-md text-sm font-medium hover:bg-accent h-10 w-10">
                <Pencil class="h-4 w-4" />
              </NuxtLink>
              <button class="inline-flex items-center justify-center rounded-md text-sm font-medium hover:bg-accent h-10 w-10" @click="handleDelete(plan.id)">
                <Trash2 class="h-4 w-4" />
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Plus, Pencil, Trash2, Upload, AlertTriangle } from 'lucide-vue-next'

definePageMeta({ layout: 'admin' })

const { t } = useI18n()
const localePath = useLocalePath()

const plans = ref<any[]>([])
const loading = ref(true)
const importing = ref(false)
const activeTab = ref<'subscription' | 'credits'>('subscription')
const pricingMode = ref('static')

const subscriptionPlans = computed(() => plans.value.filter(p => p.durationType !== 'credits'))
const creditPlans = computed(() => plans.value.filter(p => p.durationType === 'credits'))
const displayedPlans = computed(() => activeTab.value === 'subscription' ? subscriptionPlans.value : creditPlans.value)

const supportedLocales = ['en', 'zh-CN']
const uncoveredLocales = computed(() => {
  const covered = new Set<string>()
  plans.value.filter(p => p.isActive).forEach(p => {
    if (!p.locales) supportedLocales.forEach(l => covered.add(l))
    else p.locales.forEach((l: string) => covered.add(l))
  })
  return supportedLocales.filter(l => !covered.has(l))
})

const ssrHeaders = import.meta.server ? useRequestHeaders(['cookie']) : undefined

async function fetchPlans() {
  try {
    const data = await $fetch<{ plans: any[]; pricingMode?: string }>('/api/admin/pricing-plans', { headers: ssrHeaders })
    plans.value = data.plans || []
    if (data.pricingMode) pricingMode.value = data.pricingMode
  } catch (err) {
    console.error('Error fetching plans:', err)
  } finally {
    loading.value = false
  }
}

async function handleDelete(id: string) {
  if (!confirm(t('admin.pricing.confirmDelete'))) return
  await $fetch(`/api/admin/pricing-plans?id=${id}`, { method: 'DELETE' })
  fetchPlans()
}

async function handleToggleActive(plan: any) {
  await $fetch('/api/admin/pricing-plans', { method: 'PUT', body: { id: plan.id, isActive: !plan.isActive } })
  fetchPlans()
}

async function handleImport() {
  if (!confirm(t('admin.pricing.importConfirm'))) return
  importing.value = true
  try {
    const data = await $fetch<{ imported: number }>('/api/admin/pricing-plans/import', { method: 'POST' })
    alert(`${t('admin.pricing.importSuccess')} (${data.imported})`)
    fetchPlans()
  } finally { importing.value = false }
}

await fetchPlans()
</script>

// reference/tinyship-main/apps/next-app/app/[lang]/admin/pricing/page.tsx
'use client'

import { useEffect, useState, useCallback } from 'react'
import { useTranslation } from '@/hooks/use-translation'
import { Badge } from '@libs/react-shared/ui/badge'
import { Button } from '@libs/react-shared/ui/button'
import { Switch } from '@libs/react-shared/ui/switch'
import { Plus, Pencil, Trash2, Upload, AlertTriangle } from 'lucide-react'
import Link from 'next/link'
import { useParams } from 'next/navigation'

interface PricingPlan {
  id: string
  provider: string
  amount: string
  originalPrice: string | null
  currency: string
  durationType: string
  durationMonths: number | null
  credits: number | null
  recommended: boolean
  sortOrder: number
  isActive: boolean
  locales: string[] | null
  i18n: Record<string, { name: string; description: string }>
}

export default function AdminPricingPage() {
  const { t } = useTranslation()
  const params = useParams()
  const lang = params.lang as string
  const [plans, setPlans] = useState<PricingPlan[]>([])
  const [loading, setLoading] = useState(true)
  const [importing, setImporting] = useState(false)
  const [activeTab, setActiveTab] = useState<'subscription' | 'credits'>('subscription')
  const [pricingMode, setPricingMode] = useState<string>('static')

  const tp = t.admin?.pricing

  const fetchPlans = useCallback(async () => {
    try {
      const res = await fetch('/api/admin/pricing-plans')
      if (!res.ok) throw new Error('Failed to fetch')
      const data = await res.json()
      setPlans(data.plans || [])
      if (data.pricingMode) setPricingMode(data.pricingMode)
    } catch (err) {
      console.error('Error fetching plans:', err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { fetchPlans() }, [fetchPlans])

  const handleDelete = async (id: string) => {
    if (!confirm(tp?.confirmDelete || 'Are you sure?')) return
    const res = await fetch(`/api/admin/pricing-plans?id=${id}`, { method: 'DELETE' })
    if (res.ok) fetchPlans()
  }

  const handleToggleActive = async (plan: PricingPlan) => {
    await fetch('/api/admin/pricing-plans', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id: plan.id, isActive: !plan.isActive }),
    })
    fetchPlans()
  }

  const handleImport = async () => {
    if (!confirm(tp?.importConfirm || 'Import all static plans from config?')) return
    setImporting(true)
    try {
      const res = await fetch('/api/admin/pricing-plans/import', { method: 'POST' })
      if (res.ok) {
        const data = await res.json()
        alert(`${tp?.importSuccess} (${data.imported})`)
        fetchPlans()
      }
    } finally {
      setImporting(false)
    }
  }

  const subscriptionPlans = plans.filter(p => p.durationType !== 'credits')
  const creditPlans = plans.filter(p => p.durationType === 'credits')

  const supportedLocales = ['en', 'zh-CN']
  const coveredLocales = new Set<string>()
  plans.filter(p => p.isActive).forEach(p => {
    if (!p.locales) supportedLocales.forEach(l => coveredLocales.add(l))
    else p.locales.forEach(l => coveredLocales.add(l))
  })
  const uncoveredLocales = supportedLocales.filter(l => !coveredLocales.has(l))

  if (loading) {
    return (
      <div className="container mx-auto py-10 px-5">
        <h1 className="text-2xl font-bold mb-6">{tp?.title}</h1>
        <div className="animate-pulse text-muted-foreground">{t.common?.loading}</div>
      </div>
    )
  }

  const displayedPlans = activeTab === 'subscription' ? subscriptionPlans : creditPlans

  return (
    <div className="container mx-auto py-10 px-5">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold">{tp?.title}</h1>
          <p className="text-muted-foreground text-sm mt-1">
            {tp?.description}
            <Badge variant={pricingMode === 'dynamic' ? 'default' : 'secondary'} className="ml-2">
              {pricingMode === 'dynamic' ? tp?.mode?.dynamic : tp?.mode?.static}
            </Badge>
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleImport} disabled={importing}>
            <Upload className="h-4 w-4 mr-2" />
            {importing ? tp?.importing : tp?.importStatic}
          </Button>
          <Button asChild>
            <Link href={`/${lang}/admin/pricing/new`}>
              <Plus className="h-4 w-4 mr-2" />
              {tp?.createPlan}
            </Link>
          </Button>
        </div>
      </div>

      {uncoveredLocales.length > 0 && pricingMode === 'dynamic' && (
        <div className="flex items-center gap-2 p-3 mb-4 bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-800 rounded-md">
          <AlertTriangle className="h-4 w-4 text-yellow-600" />
          <span className="text-sm text-yellow-800 dark:text-yellow-200">
            {tp?.localeCoverageWarning} [{uncoveredLocales.join(', ')}]
          </span>
        </div>
      )}

      <div className="flex gap-2 mb-4">
        <Button
          variant={activeTab === 'subscription' ? 'default' : 'outline'}
          size="sm"
          onClick={() => setActiveTab('subscription')}
        >
          {tp?.tabs?.subscription} ({subscriptionPlans.length})
        </Button>
        <Button
          variant={activeTab === 'credits' ? 'default' : 'outline'}
          size="sm"
          onClick={() => setActiveTab('credits')}
        >
          {tp?.tabs?.credits} ({creditPlans.length})
        </Button>
      </div>

      {!displayedPlans.length ? (
        <p className="text-muted-foreground py-8 text-center">{tp?.noPlans}</p>
      ) : (
        <div className="border rounded-lg overflow-hidden">
          <table className="w-full text-sm">
            <thead className="bg-muted/50">
              <tr>
                <th className="px-4 py-3 text-left font-medium">{tp?.table?.name}</th>
                <th className="px-4 py-3 text-left font-medium">{tp?.table?.provider}</th>
                <th className="px-4 py-3 text-left font-medium">{tp?.table?.price}</th>
                <th className="px-4 py-3 text-left font-medium">{tp?.table?.type}</th>
                <th className="px-4 py-3 text-left font-medium">{tp?.table?.locales}</th>
                <th className="px-4 py-3 text-left font-medium">{tp?.table?.status}</th>
                <th className="px-4 py-3 text-right font-medium">{tp?.table?.actions}</th>
              </tr>
            </thead>
            <tbody>
              {displayedPlans.map(plan => (
                <tr key={plan.id} className="border-t">
                  <td className="px-4 py-3">
                    <div className="font-medium">{plan.i18n?.en?.name || plan.id}</div>
                    {plan.recommended && <Badge variant="outline" className="text-xs mt-1">{tp?.fields?.recommended}</Badge>}
                  </td>
                  <td className="px-4 py-3"><Badge variant="secondary">{plan.provider}</Badge></td>
                  <td className="px-4 py-3">
                    {plan.originalPrice && (
                      <span className="line-through text-muted-foreground mr-1">{plan.currency} {plan.originalPrice}</span>
                    )}
                    <span className="font-medium">{plan.currency} {plan.amount}</span>
                  </td>
                  <td className="px-4 py-3">
                    <Badge variant="outline">{plan.durationType}</Badge>
                    {plan.durationType === 'credits' ? ` (${plan.credits})` : plan.durationMonths ? ` (${plan.durationMonths}mo)` : ''}
                  </td>
                  <td className="px-4 py-3">
                    {plan.locales ? <span className="text-xs">{plan.locales.join(', ')}</span> : <span className="text-muted-foreground text-xs">{tp?.table?.allLocales}</span>}
                  </td>
                  <td className="px-4 py-3">
                    <Switch checked={plan.isActive} onCheckedChange={() => handleToggleActive(plan)} />
                  </td>
                  <td className="px-4 py-3 text-right">
                    <Button variant="ghost" size="icon" asChild>
                      <Link href={`/${lang}/admin/pricing/${plan.id}`}>
                        <Pencil className="h-4 w-4" />
                      </Link>
                    </Button>
                    <Button variant="ghost" size="icon" onClick={() => handleDelete(plan.id)}>
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
